[build]
command = "yarn build"
publish = "build"

[[redirects]]
force = true
from = "/api/*"
headers = {X-From = "Netlify"}
status = 200
to = "https://www.metaweather.com/api/:splat"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
